# Generated by Django 6.1 on 2026-08-31 20:21

import django.core.validators
import django.db.models.deletion
import production.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("scraper", "0005_import_legacy_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtifactDependency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("upstream_object_id", models.PositiveBigIntegerField()),
                ("upstream_version", models.PositiveIntegerField()),
                ("upstream_fingerprint", models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message="Enter a lowercase SHA-256 digest.", regex="^[0-9a-f]{64}$")])),
                ("downstream_object_id", models.PositiveBigIntegerField()),
                ("downstream_version", models.PositiveIntegerField()),
                ("relation_type", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("downstream_content_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="contenttypes.contenttype")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="artifact_dependencies", to="scraper.videoproject")),
                ("upstream_content_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="contenttypes.contenttype")),
            ],
            options={
                "ordering": ["project", "upstream_content_type", "upstream_object_id"],
                "indexes": [
                    models.Index(fields=["project", "upstream_content_type", "upstream_object_id", "upstream_version"], name="artifact_upstream_idx"),
                    models.Index(fields=["project", "downstream_content_type", "downstream_object_id", "downstream_version"], name="artifact_downstream_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("project", "upstream_content_type", "upstream_object_id", "upstream_version", "downstream_content_type", "downstream_object_id", "downstream_version", "relation_type"), name="artifact_dependency_uniq"),
                    models.CheckConstraint(condition=models.Q(("upstream_version__gte", 1)), name="artifact_upstream_ver_gte_1"),
                    models.CheckConstraint(condition=models.Q(("downstream_version__gte", 1)), name="artifact_downstream_ver_gte_1"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lineage_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("kind", models.CharField(choices=[("source_upload", "Source upload"), ("source_clip", "Source clip"), ("narration", "Narration"), ("visual", "Visual"), ("render", "Render"), ("other", "Other")], max_length=24)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("validated", "Validated"), ("approved", "Approved"), ("stale", "Stale"), ("superseded", "Superseded"), ("failed", "Failed")], default="draft", max_length=16)),
                ("display_name", models.CharField(max_length=255)),
                ("file", models.FileField(blank=True, max_length=500, upload_to=production.models.project_media_upload_to)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(message="Enter a lowercase SHA-256 digest.", regex="^[0-9a-f]{64}$")])),
                ("byte_size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("duration_seconds", models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("frame_rate", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ("has_audio", models.BooleanField(default=False)),
                ("has_video", models.BooleanField(default=False)),
                ("detected_mime_type", models.CharField(blank=True, max_length=100)),
                ("container", models.CharField(blank=True, max_length=100)),
                ("video_codec", models.CharField(blank=True, max_length=100)),
                ("audio_codec", models.CharField(blank=True, max_length=100)),
                ("origin", models.CharField(choices=[("user_upload", "User upload"), ("generated", "Generated"), ("imported", "Imported"), ("provider", "External provider")], default="user_upload", max_length=20)),
                ("source_url", models.URLField(blank=True)),
                ("rights_basis", models.CharField(choices=[("unknown", "Unknown"), ("user_owned", "User owned"), ("licensed", "Licensed"), ("permission", "Permission granted"), ("public_domain", "Public domain")], default="unknown", max_length=20)),
                ("rights_notes", models.TextField(blank=True)),
                ("consent_metadata", models.JSONField(blank=True, default=dict)),
                ("configuration_snapshot", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="media_assets_created", to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="media_assets", to="scraper.videoproject")),
            ],
            options={
                "ordering": ["project", "kind", "lineage_id", "-version"],
                "indexes": [
                    models.Index(fields=["project", "status", "kind"], name="media_project_state_idx"),
                    models.Index(fields=["checksum_sha256"], name="media_checksum_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("lineage_id", "version"), name="media_lineage_version_uniq"),
                    models.CheckConstraint(condition=models.Q(("version__gte", 1)), name="media_version_gte_1"),
                    models.CheckConstraint(condition=models.Q(("duration_seconds__isnull", True), ("duration_seconds__gte", 0), _connector="OR"), name="media_duration_gte_0"),
                    models.CheckConstraint(condition=models.Q(("frame_rate__isnull", True), ("frame_rate__gte", 0), _connector="OR"), name="media_frame_rate_gte_0"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PipelineJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("job_type", models.CharField(max_length=64)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("succeeded", "Succeeded"), ("failed", "Failed"), ("cancelled", "Cancelled")], default="queued", max_length=12)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("idempotency_key", models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message="Enter a lowercase SHA-256 digest.", regex="^[0-9a-f]{64}$")])),
                ("max_attempts", models.PositiveSmallIntegerField(default=3)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("input_fingerprint", models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message="Enter a lowercase SHA-256 digest.", regex="^[0-9a-f]{64}$")])),
                ("input_snapshot", models.JSONField(blank=True, default=dict)),
                ("configuration_snapshot", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pipeline_jobs", to="scraper.videoproject")),
                ("requested_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="pipeline_jobs_requested", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["project", "-created_at"],
                "indexes": [
                    models.Index(fields=["project", "status", "-created_at"], name="pipeline_project_state_idx"),
                    models.Index(fields=["job_type", "idempotency_key"], name="pipeline_idem_lookup_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(condition=models.Q(("status__in", ["queued", "running"])), fields=("project", "job_type", "idempotency_key"), name="pipeline_active_idem_uniq"),
                    models.CheckConstraint(condition=models.Q(("progress__gte", 0), ("progress__lte", 100)), name="pipeline_progress_range"),
                    models.CheckConstraint(condition=models.Q(("max_attempts__gte", 1)), name="pipeline_max_attempts_gte_1"),
                    models.CheckConstraint(condition=models.Q(("attempt_count__lte", models.F("max_attempts"))), name="pipeline_attempts_within_max"),
                ],
            },
        ),
    ]
