# Generated by Django 6.1 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="mediaasset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "approved")),
                fields=("lineage_id",),
                name="media_one_approved_lineage",
            ),
        ),
    ]
