# Generated by Django 6.1 on 2026-08-31 21:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0002_add_boundary_constraints"),
        ("production", "0002_media_one_approved_lineage"),
        ("scraper", "0005_import_legacy_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceClip",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.PositiveIntegerField()),
                ("status", models.CharField(choices=[("processing", "Processing"), ("validated", "Validated"), ("approved", "Approved"), ("failed", "Failed"), ("stale", "Stale"), ("superseded", "Superseded")], default="processing", max_length=16)),
                ("input_fingerprint", models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message="Enter a lowercase SHA-256 digest.", regex="^[0-9a-f]{64}$")])),
                ("requested_start_seconds", models.DecimalField(decimal_places=3, max_digits=12)),
                ("requested_end_seconds", models.DecimalField(decimal_places=3, max_digits=12)),
                ("padding_before_seconds", models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ("padding_after_seconds", models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ("actual_start_seconds", models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ("actual_end_seconds", models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ("expected_duration_seconds", models.DecimalField(decimal_places=3, max_digits=12)),
                ("actual_duration_seconds", models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ("validation_result", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="source_clips_approved", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="source_clips_created", to=settings.AUTH_USER_MODEL)),
                ("pipeline_job", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="source_clip", to="production.pipelinejob")),
                ("processed_asset", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="source_clip_output", to="production.mediaasset")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="source_clips", to="scraper.videoproject")),
                ("selected_segment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="source_clips", to="analysis.segmentselection")),
                ("source_asset", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="source_clip_inputs", to="production.mediaasset")),
            ],
            options={
                "ordering": ["project", "selected_segment", "-version"],
                "indexes": [models.Index(fields=["project", "status", "-created_at"], name="source_clip_project_state_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("selected_segment", "version"), name="source_clip_selection_ver_uniq"),
                    models.UniqueConstraint(condition=models.Q(("status", "approved")), fields=("selected_segment",), name="source_clip_one_approved"),
                    models.CheckConstraint(condition=models.Q(("version__gte", 1)), name="source_clip_version_gte_1"),
                    models.CheckConstraint(condition=models.Q(("requested_start_seconds__gte", 0)), name="source_clip_requested_start_gte_0"),
                    models.CheckConstraint(condition=models.Q(("requested_end_seconds__gt", models.F("requested_start_seconds"))), name="source_clip_requested_time_order"),
                    models.CheckConstraint(condition=models.Q(("padding_before_seconds__gte", 0), ("padding_after_seconds__gte", 0)), name="source_clip_padding_gte_0"),
                    models.CheckConstraint(condition=models.Q(("expected_duration_seconds__gt", 0)), name="source_clip_expected_duration_gt_0"),
                    models.CheckConstraint(condition=models.Q(("actual_duration_seconds__isnull", True), ("actual_duration_seconds__gt", 0), _connector="OR"), name="source_clip_actual_duration_gt_0"),
                    models.CheckConstraint(condition=models.Q(("actual_start_seconds__isnull", True), ("actual_start_seconds__gte", 0), _connector="OR"), name="source_clip_actual_start_gte_0"),
                    models.CheckConstraint(condition=models.Q(("actual_end_seconds__isnull", True), ("actual_start_seconds__isnull", True), ("actual_end_seconds__gt", models.F("actual_start_seconds")), _connector="OR"), name="source_clip_actual_time_order"),
                ],
            },
        ),
    ]
