# Generated by Django 6.1 on 2026-09-06 09:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_sourceclip'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinejob',
            name='available_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='lease_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
