# Generated by Django 6.1 on 2026-09-11 21:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0001_initial'),
        ('production', '0004_job_leases'),
        ('scraper', '0005_import_legacy_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='NarrationTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('script_text', models.TextField()),
                ('script_fingerprint', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Enter a lowercase SHA-256 digest.', regex='^[0-9a-f]{64}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media_asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='narration_take', to='production.mediaasset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.videoproject')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='narration_takes', to='editorial.reactionblock')),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('reaction', 'version'), name='narration_reaction_version_uniq'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='narration_version_gte_1')],
            },
        ),
    ]
