"""
Django settings for YoutubeContent project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import secrets
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    if value.lower() not in {"true", "false", "1", "0"}:
        raise ImproperlyConfigured(f"{name} must be true, false, 1, or 0.")
    return value.lower() in {"true", "1"}


def env_list(name, default=""):
    return [item.strip() for item in os.environ.get(name, default).split(",") if item.strip()]


ENVIRONMENT = os.environ.get("DJANGO_ENV", "development")
if ENVIRONMENT not in {"development", "production"}:
    raise ImproperlyConfigured("DJANGO_ENV must be development or production.")
DEBUG = env_bool("DJANGO_DEBUG", ENVIRONMENT == "development")
if ENVIRONMENT == "production" and DEBUG:
    raise ImproperlyConfigured("DJANGO_DEBUG must be false in production.")
PRODUCTION = ENVIRONMENT == "production" or not DEBUG
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "")
LOCAL_SECRET_KEY_FILE = BASE_DIR / ".local-secret-key"
if not SECRET_KEY:
    if PRODUCTION:
        raise ImproperlyConfigured("Set DJANGO_SECRET_KEY before running in production.")
    # No settings-import writes: init_local_settings creates a persistent local key.
    SECRET_KEY = (
        LOCAL_SECRET_KEY_FILE.read_text(encoding="utf-8").strip()
        if LOCAL_SECRET_KEY_FILE.exists()
        else secrets.token_urlsafe(64)
    )
if not SECRET_KEY:
    raise ImproperlyConfigured("The local secret key file is empty.")

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,[::1]" if DEBUG else "")
if PRODUCTION and (not ALLOWED_HOSTS or "*" in ALLOWED_HOSTS):
    raise ImproperlyConfigured("Set DJANGO_ALLOWED_HOSTS to explicit production hostnames.")
CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS")
SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", PRODUCTION)
SESSION_COOKIE_SECURE = PRODUCTION
CSRF_COOKIE_SECURE = PRODUCTION
SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "3600" if PRODUCTION else "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", False)
# Enable only behind a proxy that strips incoming forwarding headers and sets its own.
if env_bool("DJANGO_TRUST_PROXY_HTTPS", False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "users",
    "scraper",
    "analysis",
    "production",
    "editorial",

    "django.contrib.sites",
    "allauth",
    "allauth.account",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'YoutubeContent.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'YoutubeContent.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get("DJANGO_DB_PATH", str(BASE_DIR / "db.sqlite3")),
        'OPTIONS': {'timeout': 20},
    }
}
if os.environ.get("DJANGO_TEST_DB_PATH"):
    DATABASES["default"]["TEST"] = {"NAME": os.environ["DJANGO_TEST_DB_PATH"]}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = Path(os.environ.get("DJANGO_STATIC_ROOT", str(BASE_DIR / "staticfiles")))
MEDIA_URL = "/media/"
MEDIA_ROOT = Path(os.environ.get("DJANGO_MEDIA_ROOT", str(BASE_DIR / "media")))

# Media processing limits and worker recovery timings.
PIPELINE_LEASE_SECONDS = int(os.environ.get("PIPELINE_LEASE_SECONDS", "30"))
PIPELINE_HEARTBEAT_SECONDS = int(os.environ.get("PIPELINE_HEARTBEAT_SECONDS", "5"))
PIPELINE_RETRY_DELAY_SECONDS = int(os.environ.get("PIPELINE_RETRY_DELAY_SECONDS", "5"))
PRODUCTION_MAX_UPLOAD_BYTES = int(
    os.environ.get("PRODUCTION_MAX_UPLOAD_BYTES", 500 * 1024 * 1024)
)
PRODUCTION_ALLOWED_MEDIA_EXTENSIONS = (
    ".mp4",
    ".mov",
    ".mkv",
    ".webm",
    ".mp3",
    ".wav",
    ".m4a",
    ".aac",
    ".png",
    ".jpg",
    ".jpeg",
    ".webp",
)
FFPROBE_EXECUTABLE = os.environ.get("FFPROBE_EXECUTABLE", "ffprobe")
FFPROBE_TIMEOUT_SECONDS = int(os.environ.get("FFPROBE_TIMEOUT_SECONDS", 15))
FFMPEG_EXECUTABLE = os.environ.get("FFMPEG_EXECUTABLE", "ffmpeg")
FFMPEG_TIMEOUT_SECONDS = int(os.environ.get("FFMPEG_TIMEOUT_SECONDS", 180))
SOURCE_CLIP_MAX_PADDING_SECONDS = 10
SOURCE_CLIP_DURATION_TOLERANCE_SECONDS = 0.35
SOURCE_CLIP_MAX_WIDTH = 3840
SOURCE_CLIP_MAX_HEIGHT = 2160
SOURCE_CLIP_MAX_FRAME_RATE = 120
from YoutubeContent.local_settings import read_local_ai_settings

_local_ai_settings = read_local_ai_settings(BASE_DIR / "env.py") if not PRODUCTION else {}
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", _local_ai_settings.get("OPENAI_API_KEY", ""))
OPENAI_RESEARCH_MODEL = os.environ.get(
    "OPENAI_RESEARCH_MODEL", _local_ai_settings.get("OPENAI_RESEARCH_MODEL", "gpt-6-astra")
)
OPENAI_REACTION_MODEL = os.environ.get(
    "OPENAI_REACTION_MODEL", _local_ai_settings.get("OPENAI_REACTION_MODEL", OPENAI_RESEARCH_MODEL)
)
OPENAI_ANALYSIS_MODEL = os.environ.get(
    "OPENAI_ANALYSIS_MODEL", _local_ai_settings.get("OPENAI_ANALYSIS_MODEL", OPENAI_RESEARCH_MODEL)
)
del _local_ai_settings
SITE_ID = 1

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {"default": {"BACKEND": "django.core.mail.backends.console.EmailBackend"}}
if PRODUCTION or os.environ.get("DJANGO_SMTP_HOST"):
    smtp_host = os.environ.get("DJANGO_SMTP_HOST", "")
    if not smtp_host:
        raise ImproperlyConfigured("Set DJANGO_SMTP_HOST for production email.")
    MAILERS["default"] = {
        "BACKEND": "django.core.mail.backends.smtp.EmailBackend",
        "OPTIONS": {
            "host": smtp_host,
            "port": int(os.environ.get("DJANGO_SMTP_PORT", "587")),
            "username": os.environ.get("DJANGO_SMTP_USERNAME", ""),
            "password": os.environ.get("DJANGO_SMTP_PASSWORD", ""),
            "use_tls": env_bool("DJANGO_SMTP_USE_TLS", True),
            "use_ssl": env_bool("DJANGO_SMTP_USE_SSL", False),
            "timeout": int(os.environ.get("DJANGO_SMTP_TIMEOUT", "10")),
        },
    }
DEFAULT_FROM_EMAIL = os.environ.get("DJANGO_DEFAULT_FROM_EMAIL", "webmaster@localhost")
SERVER_EMAIL = os.environ.get("DJANGO_SERVER_EMAIL", DEFAULT_FROM_EMAIL)
LOGIN_REDIRECT_URL = "/"
ACCOUNT_LOGOUT_REDIRECT_URL = "/"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

