# Generated by Django 6.1 on 2026-09-01 00:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0003_sourceclip'),
        ('scraper', '0005_import_legacy_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('stale', 'Stale'), ('superseded', 'Superseded')], default='draft', max_length=16)),
                ('input_fingerprint', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Enter a lowercase SHA-256 digest.', regex='^[0-9a-f]{64}$')])),
                ('research_question', models.CharField(max_length=500)),
                ('editorial_focus', models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)])),
                ('configuration_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_packages_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_packages', to='scraper.videoproject')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_packages_reviewed', to=settings.AUTH_USER_MODEL)),
                ('source_clip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_packages', to='production.sourceclip')),
            ],
            options={
                'ordering': ['source_clip', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ReactionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('draft', 'Draft'), ('approved', 'Approved'), ('failed', 'Failed'), ('stale', 'Stale'), ('superseded', 'Superseded')], default='generating', max_length=16)),
                ('input_fingerprint', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Enter a lowercase SHA-256 digest.', regex='^[0-9a-f]{64}$')])),
                ('reframe', models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)])),
                ('focus', models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)])),
                ('reaction_type', models.CharField(choices=[('agreement', 'Agreement'), ('disagreement', 'Disagreement'), ('critique', 'Critique'), ('context', 'Additional context'), ('correction', 'Correction'), ('mixed', 'Mixed')], max_length=16)),
                ('evaluation', models.TextField(validators=[django.core.validators.MaxLengthValidator(8000)])),
                ('mini_essay_thesis', models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('mini_essay_script', models.TextField(validators=[django.core.validators.MaxLengthValidator(16000)])),
                ('conclusion', models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)])),
                ('bridge', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('combined_script', models.TextField(validators=[django.core.validators.MaxLengthValidator(40000)])),
                ('rationale', models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)])),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('provider_model', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(blank=True, max_length=64)),
                ('algorithm_version', models.CharField(max_length=64)),
                ('configuration_snapshot', models.JSONField(blank=True, default=dict)),
                ('used_fallback', models.BooleanField(default=False)),
                ('approval_attestation', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reaction_blocks_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reaction_blocks_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_blocks', to='scraper.videoproject')),
                ('source_clip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reaction_blocks', to='production.sourceclip')),
                ('research_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reaction_blocks', to='editorial.researchpackage')),
            ],
            options={
                'ordering': ['source_clip', '-version'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=1000)),
                ('title', models.CharField(max_length=500)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('retrieved_on', models.DateField()),
                ('classification', models.CharField(choices=[('supports', 'Supports'), ('contradicts', 'Contradicts'), ('uncertain', 'Uncertain'), ('context', 'Context')], max_length=16)),
                ('finding', models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)])),
                ('relevance', models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)])),
                ('permitted_excerpt', models.TextField(blank=True, help_text='Store only a short excerpt when permitted.', validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('citation_metadata', models.JSONField(blank=True, default=dict)),
                ('snapshot_reference', models.URLField(blank=True, max_length=1000)),
                ('source_origin', models.CharField(choices=[('manual', 'Entered by user'), ('provider', 'Suggested by provider')], default='manual', max_length=16)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_sources_created', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_sources_verified', to=settings.AUTH_USER_MODEL)),
                ('research_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_sources', to='editorial.researchpackage')),
            ],
            options={
                'ordering': ['research_package', 'title', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ReactionClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)])),
                ('claim_type', models.CharField(choices=[('factual', 'Factual'), ('opinion', 'Opinion'), ('inference', 'Inference')], max_length=16)),
                ('citation_note', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reaction_claims', to='editorial.evidencesource')),
                ('reaction_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='editorial.reactionblock')),
                ('transcript_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reaction_claims', to='scraper.transcriptchunk')),
            ],
            options={
                'ordering': ['reaction_block', 'order'],
                'constraints': [models.UniqueConstraint(fields=('reaction_block', 'order'), name='reaction_claim_order_uniq'), models.CheckConstraint(condition=models.Q(('order__gte', 1)), name='reaction_claim_order_gte_1'), models.CheckConstraint(condition=models.Q(models.Q(('claim_type', 'factual'), _negated=True), ('transcript_chunk__isnull', False), ('evidence_source__isnull', False), _connector='OR'), name='factual_claim_has_citation')],
            },
        ),
        migrations.AddIndex(
            model_name='researchpackage',
            index=models.Index(fields=['project', 'status', '-created_at'], name='research_project_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='researchpackage',
            constraint=models.UniqueConstraint(fields=('source_clip', 'version'), name='research_clip_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='researchpackage',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ready')), fields=('source_clip',), name='research_one_ready_clip'),
        ),
        migrations.AddConstraint(
            model_name='researchpackage',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='research_version_gte_1'),
        ),
        migrations.AddIndex(
            model_name='reactionblock',
            index=models.Index(fields=['project', 'status', '-created_at'], name='reaction_project_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='reactionblock',
            constraint=models.UniqueConstraint(fields=('source_clip', 'version'), name='reaction_clip_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='reactionblock',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('source_clip',), name='reaction_one_approved_clip'),
        ),
        migrations.AddConstraint(
            model_name='reactionblock',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='reaction_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='evidencesource',
            constraint=models.UniqueConstraint(fields=('research_package', 'source_url'), name='evidence_package_url_uniq'),
        ),
    ]
