# Generated by Django 6.1 on 2026-09-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0004_reaction_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactiontimelineitem',
            name='included',
            field=models.BooleanField(default=True),
        ),
    ]
