# Generated by Django 6.1 on 2026-09-13 10:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0005_reaction_timeline_editing'),
        ('production', '0005_narration_take'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionProductionAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for production'), ('stale', 'Stale')], default='draft', max_length=16)),
                ('input_fingerprint', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Enter a lowercase SHA-256 digest.', regex='^[0-9a-f]{64}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reaction_production_assemblies_created', to=settings.AUTH_USER_MODEL)),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_assemblies', to='editorial.reactiontimeline')),
            ],
            options={
                'ordering': ['timeline', '-version'],
            },
        ),
        migrations.CreateModel(
            name='TimelineNarrationTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('script_text', models.TextField()),
                ('script_fingerprint', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Enter a lowercase SHA-256 digest.', regex='^[0-9a-f]{64}$')])),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_narration_takes_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_narration_takes_created', to=settings.AUTH_USER_MODEL)),
                ('media_asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='timeline_narration_take', to='production.mediaasset')),
                ('timeline_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='narration_takes', to='editorial.reactiontimelineitem')),
            ],
            options={
                'ordering': ['timeline_item', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ReactionProductionAssemblyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('transcript_text', models.TextField()),
                ('source_start_seconds', models.FloatField(blank=True, null=True)),
                ('source_end_seconds', models.FloatField(blank=True, null=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='editorial.reactionproductionassembly')),
                ('source_clip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reaction_assembly_items', to='production.sourceclip')),
                ('timeline_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assembly_items', to='editorial.reactiontimelineitem')),
                ('narration_take', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assembly_items', to='editorial.timelinenarrationtake')),
            ],
            options={
                'ordering': ['assembly', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='reactionproductionassembly',
            constraint=models.UniqueConstraint(fields=('timeline', 'version'), name='reaction_assembly_timeline_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='reactionproductionassembly',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='reaction_assembly_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='timelinenarrationtake',
            constraint=models.UniqueConstraint(fields=('timeline_item', 'version'), name='timeline_narration_item_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='timelinenarrationtake',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='timeline_narration_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='reactionproductionassemblyitem',
            constraint=models.UniqueConstraint(fields=('assembly', 'order'), name='reaction_assembly_item_order_uniq'),
        ),
        migrations.AddConstraint(
            model_name='reactionproductionassemblyitem',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1)), name='reaction_assembly_item_order_gte_1'),
        ),
    ]
