# Generated by Django 6.1 on 2026-09-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0006_reaction_production_handoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactiontimeline',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('recording', 'Recording in progress'), ('ready', 'Ready for production'), ('stale', 'Stale')], default='draft', max_length=16),
        ),
    ]
