# Generated by Django 6.1 on 2026-09-13 10:32

import django.db.models.deletion
import hashlib
import json
from django.conf import settings
from django.db import migrations, models


def preserve_timelines(apps, schema_editor):
    def digest(value):
        return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(",", ":"),
                                        ensure_ascii=False, allow_nan=False).encode()).hexdigest()
    Timeline = apps.get_model("editorial", "ReactionTimeline")
    for timeline in Timeline.objects.select_related("reaction_draft__plan").iterator():
        draft = timeline.reaction_draft
        payload = {"draft": draft.input_fingerprint, "plan": draft.plan.input_fingerprint,
                   "sections": list(draft.sections.values_list("pk", "reaction_text", "bridge"))}
        if timeline.input_fingerprint == digest(payload):
            payload.update(opening=draft.opening, conclusion=draft.conclusion, status=draft.status)
            timeline.input_fingerprint = digest(payload)
            timeline.status = "draft"
            timeline.save(update_fields=["input_fingerprint", "status"])
    # Earlier assemblies did not capture complete media snapshots. Preserve them as history.
    apps.get_model("editorial", "ReactionProductionAssembly").objects.update(status="stale")


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0007_reaction_timeline_recording_status'),
        ('production', '0005_narration_take'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reactionproductionassemblyitem',
            name='snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='reactiontimeline',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reactiontimeline',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recording_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reactiontimeline',
            name='reviewed_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='timelinenarrationtake',
            name='recording_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='timelinenarrationtake',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reactiontimeline',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('recording', 'Ready for recording'), ('ready', 'Recording complete'), ('stale', 'Stale')], default='draft', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='timelinenarrationtake',
            constraint=models.UniqueConstraint(condition=models.Q(('selected', True)), fields=('timeline_item',), name='one_selected_timeline_take'),
        ),
        migrations.RunPython(preserve_timelines, migrations.RunPython.noop),
    ]
