# Generated by Django 6.1 on 2026-09-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0008_recording_review_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactiontimelineitem',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
