# Generated by Django 6.1 on 2026-08-31 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraper', '0005_import_legacy_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=12)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(blank=True, max_length=64)),
                ('algorithm_version', models.CharField(max_length=64)),
                ('configuration', models.JSONField(default=dict)),
                ('used_fallback', models.BooleanField(default=False)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_runs_created', to=settings.AUTH_USER_MODEL)),
                ('source_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='scraper.sourcevideo')),
            ],
            options={
                'ordering': ['source_video', '-version'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('start_seconds', models.FloatField()),
                ('end_seconds', models.FloatField()),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('source_text', models.TextField()),
                ('topic_labels', models.JSONField(default=list)),
                ('component_scores', models.JSONField(default=dict)),
                ('aggregate_score', models.DecimalField(decimal_places=3, max_digits=6)),
                ('rationale', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='analysis.analysisrun')),
                ('end_chunk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_segments_ending_here', to='scraper.transcriptchunk')),
                ('start_chunk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_segments_starting_here', to='scraper.transcriptchunk')),
            ],
            options={
                'ordering': ['analysis_run', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SegmentSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('reviewed_start_seconds', models.FloatField(blank=True, null=True)),
                ('reviewed_end_seconds', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selections', to='analysis.analysissegment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_selections', to='scraper.videoproject')),
                ('selected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segment_selections_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['source_video', 'status', '-version'], name='analysis_run_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='analysisrun',
            constraint=models.UniqueConstraint(fields=('source_video', 'version'), name='analysis_run_source_ver_uniq'),
        ),
        migrations.AddConstraint(
            model_name='analysisrun',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='analysis_run_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='analysissegment',
            constraint=models.UniqueConstraint(fields=('analysis_run', 'order'), name='analysis_segment_order_uniq'),
        ),
        migrations.AddConstraint(
            model_name='analysissegment',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1)), name='analysis_segment_order_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='analysissegment',
            constraint=models.CheckConstraint(condition=models.Q(('end_seconds__gte', models.F('start_seconds'))), name='analysis_segment_time_order'),
        ),
        migrations.AddConstraint(
            model_name='analysissegment',
            constraint=models.CheckConstraint(condition=models.Q(('aggregate_score__gte', 0), ('aggregate_score__lte', 100)), name='analysis_segment_score_range'),
        ),
        migrations.AddConstraint(
            model_name='segmentselection',
            constraint=models.UniqueConstraint(fields=('project', 'analysis_segment'), name='selection_project_segment_uniq'),
        ),
        migrations.AddConstraint(
            model_name='segmentselection',
            constraint=models.UniqueConstraint(fields=('project', 'order'), name='selection_project_order_uniq'),
        ),
        migrations.AddConstraint(
            model_name='segmentselection',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1)), name='selection_order_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='segmentselection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reviewed_end_seconds__isnull', True), ('reviewed_start_seconds__isnull', True)), models.Q(('reviewed_end_seconds__isnull', False), ('reviewed_start_seconds__isnull', False)), _connector='OR'), name='selection_reviewed_times_pair'),
        ),
        migrations.AddConstraint(
            model_name='segmentselection',
            constraint=models.CheckConstraint(condition=models.Q(('reviewed_start_seconds__isnull', True), ('reviewed_end_seconds__gte', models.F('reviewed_start_seconds')), _connector='OR'), name='selection_reviewed_time_order'),
        ),
    ]
