# Generated by Django 6.1 on 2026-08-31 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('scraper', '0005_import_legacy_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='analysissegment',
            constraint=models.CheckConstraint(condition=models.Q(('start_seconds__gte', 0)), name='analysis_segment_start_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='segmentselection',
            constraint=models.CheckConstraint(condition=models.Q(('reviewed_start_seconds__isnull', True), ('reviewed_start_seconds__gte', 0), _connector='OR'), name='selection_reviewed_start_gte_0'),
        ),
    ]
