# Generated by Django 6.1 on 2026-09-13 20:28

from django.conf import settings
from django.db import migrations, models


def validate_existing(apps, schema_editor):
    Selection = apps.get_model("analysis", "SegmentSelection")
    invalid = list(Selection.objects.filter(reviewed_end_seconds__lte=models.F("reviewed_start_seconds")).values_list("pk", flat=True))
    if invalid:
        raise RuntimeError(f"Correct invalid selection ranges before migrating. Selection IDs: {invalid}")


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_analysissegment_editorial_recommendation'),
        ('scraper', '0006_workflowaudit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(validate_existing, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='segmentselection',
            name='selection_reviewed_time_order',
        ),
        migrations.AddConstraint(
            model_name='segmentselection',
            constraint=models.CheckConstraint(condition=models.Q(('reviewed_start_seconds__isnull', True), ('reviewed_end_seconds__gt', models.F('reviewed_start_seconds')), _connector='OR'), name='selection_reviewed_time_order'),
        ),
    ]
