# Generated by Django 6.1 on 2026-08-31 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the YouTube reaction video project', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('transcript_ready', 'Transcript Ready'), ('analysis_ready', 'Analysis Ready'), ('needs_review', 'Needs Review'), ('approved', 'Approved'), ('locked', 'Locked'), ('failed', 'Failed')], default='draft', help_text='Current pipeline stage of this project', max_length=20)),
                ('current_pipeline_stage', models.CharField(default='created', help_text='Detailed description of current stage', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Project notes and description')),
                ('expected_duration', models.IntegerField(blank=True, help_text='Expected video duration in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Video Project',
                'verbose_name_plural': 'Video Projects',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(help_text='Full URL of the YouTube video')),
                ('youtube_video_id', models.CharField(help_text='YouTube video ID (extracted from URL)', max_length=11, unique=True)),
                ('title', models.CharField(help_text='Title of the YouTube video', max_length=255)),
                ('channel', models.CharField(help_text='Channel name of the source video', max_length=255)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('thumbnail_url', models.URLField(blank=True, help_text='URL of the video thumbnail')),
                ('transcript_fetched', models.BooleanField(default=False, help_text='Whether transcript has been fetched')),
                ('transcript_status', models.CharField(choices=[('pending', 'Pending'), ('fetching', 'Fetching'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of transcript fetching', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(help_text='The project this source video belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='source_video', to='scraper.videoproject')),
            ],
            options={
                'verbose_name': 'Source Video',
                'verbose_name_plural': 'Source Videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(help_text='Order of this chunk in the transcript')),
                ('start', models.FloatField(help_text='Start time in seconds')),
                ('duration', models.FloatField(help_text='Duration of this chunk in seconds')),
                ('text', models.TextField(help_text='The transcript text for this chunk')),
                ('processed', models.BooleanField(default=False, help_text='Whether this chunk has been processed by AI analysis')),
                ('segment_type', models.CharField(blank=True, choices=[('intro', 'Intro'), ('reaction', 'Reaction'), ('analysis', 'Analysis'), ('outro', 'Outro'), ('other', 'Other')], help_text='Semantic type of this segment (assigned during analysis)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_video', models.ForeignKey(help_text='The source video this chunk belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transcript_chunks', to='scraper.sourcevideo')),
            ],
            options={
                'verbose_name': 'Transcript Chunk',
                'verbose_name_plural': 'Transcript Chunks',
                'ordering': ['source_video', 'sequence'],
                'unique_together': {('source_video', 'sequence')},
            },
        ),
    ]
