# Generated by Django 6.1 on 2026-08-31 18:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_scrapedvideo_video_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyImportConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_version', models.CharField(max_length=64)),
                ('legacy_scraped_video_id', models.PositiveBigIntegerField()),
                ('legacy_transcript_entry_id', models.PositiveBigIntegerField(default=0, help_text='Legacy entry primary key, or 0 for a video-level issue.')),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('error', 'Error')], max_length=10)),
                ('reason_code', models.CharField(max_length=64)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['legacy_scraped_video_id', 'reason_code'],
                'constraints': [models.UniqueConstraint(fields=('batch_version', 'legacy_scraped_video_id', 'legacy_transcript_entry_id', 'reason_code'), name='unique_legacy_import_issue')],
            },
        ),
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('expected_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('transcript_ready', 'Transcript ready'), ('approved', 'Approved'), ('archived', 'Archived'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField()),
                ('youtube_video_id', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid 11-character YouTube video ID.', regex='^[A-Za-z0-9_-]{11}$')])),
                ('title', models.CharField(max_length=255)),
                ('channel', models.CharField(blank=True, max_length=255)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('transcript_status', models.CharField(choices=[('pending', 'Pending'), ('fetching', 'Fetching'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('legacy_scraped_video_id', models.PositiveBigIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_videos', to='scraper.videoproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('start_seconds', models.FloatField()),
                ('duration_seconds', models.FloatField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_chunks', to='scraper.sourcevideo')),
            ],
            options={
                'ordering': ['source_video', 'sequence'],
                'constraints': [models.UniqueConstraint(fields=('source_video', 'sequence'), name='unique_transcript_chunk_sequence'), models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='chunk_sequence_gte_1'), models.CheckConstraint(condition=models.Q(('start_seconds__gte', 0)), name='chunk_start_gte_0'), models.CheckConstraint(condition=models.Q(('duration_seconds__gte', 0)), name='chunk_duration_gte_0')],
            },
        ),
        migrations.AddIndex(
            model_name='videoproject',
            index=models.Index(fields=['owner', 'status'], name='project_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcevideo',
            index=models.Index(fields=['project', '-created_at'], name='source_project_saved_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcevideo',
            constraint=models.UniqueConstraint(fields=('project', 'youtube_video_id'), name='unique_project_youtube_video'),
        ),
    ]
